Fix problem when --devel mod is used
It renames feature file after test to original name to not rename local project
files

diff --git a/dnf-docker-test/launch-test b/dnf-docker-test/launch-test
--- a/dnf-docker-test/launch-test
+++ b/dnf-docker-test/launch-test
@@ -3,5 +3,10 @@ set -xeuo pipefail
 
 httpd -k start
 new_name=${1}-${2}
-mv /behave/${1}.feature /behave/${new_name}.feature
+EXIT_STATUS=0
+cp /tests/${1}.feature /behave/${new_name}.feature || EXIT_STATUS=1
+if [ "$EXIT_STATUS" = 1 ]; then
+    >&2 echo "Feature file ${1}.feature not found"
+    exit 1
+fi
 behave-2 -i $new_name -D dnf_cmd=$2 --junit --junit-directory /junit/ /behave/
